server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 下面是2个eureka注册中心集群的配置
      #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true
#ribbon:
#  ReadTimeout: 12000
#  ConnectTimeout: 2000

cloud-payment-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  client:
    config:
      cloud-payment-service:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
