server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  ## GateWay配置
  cloud:
    gateway:
      routes:
      - id: payment_routh  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001  # 匹配后提供服务的路由地址,静态uri
        uri: lb://cloud-payment-service # 动态路由地址,可以使用这个服务提供者中的所有实例,默认按照性能计算的负载均衡
        predicates:
          - Path=/payment/get/**,/payment/hystrix/get/**  # 断言，路径相匹配的进行路由

      - id: payment_routh2  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
        # uri: http://localhost:8001  # 匹配后提供服务的路由地址
        uri: lb://cloud-payment-service # 动态路由地址,可以使用这个服务提供者中的所有实例,默认按照性能计算的负载均衡
        predicates:
          - Path=/payment/lb/**  # 断言，路径相匹配的进行路由
          - After=2021-02-14T12:26:07.054+08:00[Asia/Shanghai]

# 注册进 eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true